import "../globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarMd from "@/app/(main routes)/components/NavbarMd";
import SidebarMd from "@/app/(main routes)/components/SidebarMd";
import NavbarSm from "./components/NavbarSm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased `}
      >
        <SidebarMd />
        <main className=" lg:ms-75 md:ms-65 ">
          <NavbarMd />
          <NavbarSm />
          {children}
        </main>
      </body>
    </html>
  );
}
